[project]
name = "vit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "simux0072", email = "yugenshiro@proton.me" }
]
requires-python = ">=3.14"
dependencies = [
  "numpy>=2.5.1",
  "torch>=2.11.0",
  "torchvision>=0.26.0",
]

[[tool.uv.index]]
name = "pytorch-cu132"
url = "https://download.pytorch.org/whl/cu132"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cu132", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu132", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[project.scripts]
vit = "vit:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
